name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types: 
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull docker image
      run: sudo docker pull rkundula/ci_cd:latest
    - name: Delete old container if it exists
      run: sudo docker rm -f ci_cd_container || true
    - name: Run new container
      run: sudo docker run -d -p 8000:8080 --name ci_cd_container rkundula/ci_cd:latest
