name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env: 
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: docker login -u rkundula -p $DOCKER_PASS
    - name: Build Docker image
      run: docker build -t ci_cd .
    - name: Tag docker image
      run: docker tag ci_cd:latest rkundula/ci_cd:latest
    - name: Push docker image
      run: docker push rkundula/ci_cd:latest
